#%RAML 1.0
title: Mule Service API
version: 0.0.1
baseUri: https://localhost:8081/api

/getresult:
  get:
    description: Returns the API version string
    responses:
      200:
        body:
          application/json:
            example: "0.0.1"