name: Build & Deploy to CloudHub 2.0

on:
  push:
    branches: [ main ]
  workflow_dispatch:       # allow manual runs

env:
  # --- ❶ Values you may tweak once and forget -------------------------------
  APP_NAME: mule-service            # <artifactId> in pom.xml
  RUNTIME_VERSION: 4.4.0            # minMuleVersion / pom.xml
  REGION: ap-southeast-2            # pick the CH2 region you use
  WORKER_SIZE: CH2_MEDIUM           # CH2_SMALL | CH2_MEDIUM | CH2_LARGE …
  REPLICAS: 1                       # number of workers
  BUSINESS_GROUP: mule-test         # your business group name
  ENVIRONMENT: sandbox              # your Anypoint environment
  # -------------------------------------------------------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check‑out source
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          maven-version: 3.8.8      # 👈 stays compatible with mule‑maven‑plugin 3.8.0
          cache: maven 
        
      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Build Mule application
        run: mvn -B clean package -DmuleDeploy

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-app
          path: |
            target/*.jar                # mule-service-<version>-mule-application.jar
  # -------------------------------------------------------------------------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production           # optional GitHub env for approvals
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-app

      - name: Install Anypoint CLI v4
        run: npm install -g anypoint-cli-v4

      - name: Log in to Anypoint
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        run: |
          # Non‑interactive login (token cached in ~/.anypoint)
          anypoint-cli-v4 --client_id "$ANYPOINT_CLIENT_ID" \
                          --client_secret "$ANYPOINT_CLIENT_SECRET" \
                          --no-interactive account:login

      - name: Select business group & environment
        run: |
          anypoint-cli-v4 account:use "$BUSINESS_GROUP"
          anypoint-cli-v4 environment:use "$ENVIRONMENT"

      - name: Deploy to CloudHub 2.0
        run: |
          FILE=$(ls *.jar | head -n 1)
          echo "Deploying $FILE to CloudHub 2.0 ..."
          anypoint-cli-v4 runtime-mgr cloudhub2 applications deploy \
            --name "$APP_NAME" \
            --file "$FILE" \
            --runtime "$RUNTIME_VERSION" \
            --region "$REGION" \
            --worker-type "$WORKER_SIZE" \
            --replicas "$REPLICAS" \
            --redeploy             # idempotent: updates if app exists
