name: Build & Deploy to CloudHub 2.0

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: mule-service
  RUNTIME_VERSION: 4.4.0
  REGION: ap-southeast-2
  WORKER_SIZE: CH2_MEDIUM
  REPLICAS: 1
  BUSINESS_GROUP: mule-test          # organisation / business‑group name
  ENVIRONMENT: sandbox               # Anypoint environment

jobs:
  # ------------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8 + Maven 3.9
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Build Mule application
        run: mvn -B clean package -DmuleDeploy

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-app
          path: target/*.jar
          if-no-files-found: error      # fail fast if build produced nothing
  # ------------------------------------------------------------------------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production            # (optional) GitHub env for approvals
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-app

      # ---------------------------------------------------------------
      # CLI install & one‑time, non‑interactive configuration
      # ---------------------------------------------------------------
      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli

      - name: Configure Anypoint CLI
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        run: |
          # Store credentials in CLI config (avoids prompts later)
          anypoint-cli configure set client_id "$ANYPOINT_CLIENT_ID"
          anypoint-cli configure set client_secret "$ANYPOINT_CLIENT_SECRET"

          # Pre‑select business group & environment so commands are non‑interactive
          anypoint-cli configure set organization "$BUSINESS_GROUP"
          anypoint-cli configure set environment "$ENVIRONMENT"

          # (Optional) silence the “telemetry” question forever
          anypoint-cli configure set telemetry off

      # ---------------------------------------------------------------
      # Deploy the freshly‑built JAR to CloudHub 2.0
      # ---------------------------------------------------------------
      - name: Deploy to CloudHub 2.0
        run: |
          FILE=$(ls *.jar | head -n 1)
          echo "Deploying $FILE to CloudHub 2.0 …"

          anypoint-cli runtime-mgr cloudhub2 applications deploy \
            --name "$APP_NAME" \
            --file "$FILE" \
            --runtime "$RUNTIME_VERSION" \
            --region "$REGION" \
            --worker-type "$WORKER_SIZE" \
            --replicas "$REPLICAS" \
            --redeploy        \
            --yes             # auto‑confirm overwrite if app already exists
