name: Deploy MuleSoft API

on:
  push:
    branches: [ none ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create minimal MuleSoft app
        run: |
          # Create directory structure
          mkdir -p mule-app/src/main/mule
          
          # Create the Mule XML config with the /getresult endpoint
          cat > mule-app/src/main/mule/main.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <mule xmlns="http://www.mulesoft.org/schema/mule/core"
                xmlns:http="http://www.mulesoft.org/schema/mule/http"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="
                  http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
                  http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
          
              <http:listener-config name="api-http-listener-config">
                  <http:listener-connection host="0.0.0.0" port="8081" />
              </http:listener-config>
          
              <flow name="get-result-flow">
                  <http:listener config-ref="api-http-listener-config" path="/getresult"/>
                  <set-payload value="0.0.1"/>
              </flow>
          </mule>
          EOF
          
          # Create the minimum required descriptor
          cat > mule-app/mule-artifact.json << 'EOF'
          {
            "minMuleVersion": "4.4.0",
            "name": "mule-service"
          }
          EOF

      - name: Package as JAR
        run: |
          cd mule-app
          jar -cf mule-service.jar src mule-artifact.json
          cd ..

      - name: Get Anypoint token
        id: get_token
        run: |
          TOKEN_RESPONSE=$(curl -s -X POST "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token" \
            -H "Content-Type: application/json" \
            -d "{\"client_id\": \"${{ secrets.ANYPOINT_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.ANYPOINT_CLIENT_SECRET }}\", \"grant_type\": \"client_credentials\"}")
          
          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | grep -o '"access_token":"[^"]*' | sed 's/"access_token":"//')
          
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to get access token"
            echo "Response: $TOKEN_RESPONSE"
            exit 1
          fi
          
          echo "::add-mask::$ACCESS_TOKEN"
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Deploy to CloudHub
        run: |
          curl -X POST "https://anypoint.mulesoft.com/cloudhub/api/v2/applications" \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.access_token }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@mule-app/mule-service.jar" \
            -F "autoStart=true" \
            -F "appInfoJson={\"domain\":\"mule-service\",\"workers\":{\"amount\":1,\"type\":{\"name\":\"Micro\"}},\"region\":\"us-east-1\",\"muleVersion\":\"4.4.0\"}"